### ISSUE TITLE
关于在Xcode上编译dylib的问题

### ISSUE THREAD

**Issue by a455455b** [hdw09/CIHexoBlog#1]
大佬,求教,拜读了您的文章,还是一头雾水啊

**Comment by hdw09** [comment]
什么问题，描述一下啊 @a455455b

**Comment by a455455b** [comment]
大佬  终于出现了 我到现在还没明白 您的文章说的Xcode编译oclint自定义规则那里应该咋操作  那个oclintexe是个啥呀

**Comment by a455455b** [comment]
我现在调试自定义规则很头疼啊

**Comment by a455455b** [comment]
大佬在吗@hdw09

**Comment by hdw09** [comment]
就是oclint的程序啊   1208576491  加我QQ聊吧

**Comment by a455455b** [comment]
@hdw09 大佬 我加你啦

**Comment by hdw09** [comment]
done
